language: scala

scala: 
- 2.11.8

jdk:
- oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

env:
  global:
  - secure: "FNle4CtOF9meB3eve8kVU3GDdjmhnywtqCsYk7957IYVAj8Lkfg9I0R8mFlM4DpK9r/bI8uyMdwYaUzcmQR5pPH9wsy1pyD0O/LC+gSZ3a9mq2GaaIFRDrmQPzyVPUqJlUQFNoXk7XIR/65rjBClYvTQCiIVyQuvgx43lbFZd1Zejz2ZSkbIZWkzGLTp8Zc4UinqybUspDYXUy/PWL+lqxGxDiUrrRu3A2Kpdv/1f+c2JeSHmqm4J24rR2A034m616eO02FF44g9w+CXBci2UtRItmNy4A63ysaOO1ZEXbYLSCxxq9X2plXXSFn4bTtV+HMbf0PujlAmvAI+YhBz2l3JPBP+EUK5/7Y1CaRnwvVcNkVBe6BHoKp/mCtAt0W+JfOApac8z5v2NW4vCppAbxnIaIsJtmOYgodhRKpKW8iswsGJAYWKk7cTyJrU/51ZlNXOMwTWlMnB6uUvpagmV1vzsuoB1rHJ/wERJSHhbQ2CQEhiBgbJIb1xPuf595kCX0JLZtGEyyZBVwept/XXx6E3sPDVLwt+umMMEuBxPz2HfK1nFyqF9vqrkWCvMjRamqTzG7/t8iqIlQVxE0xXy3KWnvvCtfIioLvq3tBJ8Hfw52UBo+GGrjaCuX1nxCdJfniNgeV5y1Z5F0GeRxVG45ucBgV2zXIBKgm9KLJ7Svk="
  - secure: "ObTluRQ4neztsn6VpEKoNUplAqyYnJQADuFPfhmcSYTwyPs6qrnPrRPtXm/wOOAxDpeAYxVTiyIBZY6d7w5XoKINVqzSjekgQZ2kchDttaxpGC0lywBiAObu8kkZ3zRcmFcbsC1NJQkIY95yMMZz0aaN3Z4PGUJq/iQD1h2UklLJbRFTRZwUQB6qlssA72GTyDeE4lFFghlqKhFLcVWxJ42JtfW3O97xnRP6bEIMbjDiYxFoaPE/CDJYbBAjT02ZpMMo/PJ/pTmtei0xPMLeECEHw/ALDyVNgTIF5tJvRjVI2pzfYiy924BAJxi+IMMJe/N26v/dxSERu0r36yWU6DK4LqXdOuTsXRfFbGAqNmpONgLdHHVzBzdjcZusB34o3/g/wbXI3Z1HITPJW9fSTU2AD/bVWgqN7fotkUW2+MsByzAGVR0EbJfPRrUJaRt1NLiuXjbDpjyh4PstWsgejFHpM2DDT5VCMd/XqsMjl0T4JaBJ42Pyemd5CTujZRfrda3pfQupR15JDPqkQdaR33/g7yzu/ERqly3NLY3JoKbXU1FakKCVFgGHX+bqpFjpdOzI5B1M2I+w1iR1lVcUg1orIc5vrR7Bc7l7H66W/FryKe3KPXTpQkYBw7J4lidWCNqJo807HlZQ7mvRdWTHzz1rJg4Leh+57ihYeMedFJs="

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test
  - (test $TRAVIS_SCALA_VERSION == "2.11.8" && sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-Xms2g -J-Xmx2g docs/tut)

after_success:
  - >
    test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "series/0.1" &&
    sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh" &&
    sbt 'set version := version.value + "." + System.getenv("TRAVIS_BUILD_NUMBER")' publish